# Generated by Django 4.0.5 on 2023-01-05 06:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CountriesListModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='CandidateFormModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('phone', models.IntegerField(unique=True)),
                ('phone2', models.IntegerField(null=True)),
                ('status', models.BooleanField(default=False)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AgentUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('view_password', models.CharField(max_length=100, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AgentFormModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_dob', models.DateField()),
                ('candidate_high_edu', models.TextField()),
                ('specify_country_exp', models.TextField(null=True)),
                ('preferred_country', models.CharField(max_length=150)),
                ('any_physical_challenge', models.BooleanField(default=False)),
                ('specify_physical_challenge', models.TextField(null=True)),
                ('any_relatives', models.BooleanField(default=True)),
                ('specify_any_relatives', models.TextField(null=True)),
                ('select_status', models.BooleanField(default=True)),
                ('specify_select_status', models.TextField(null=True)),
                ('marital_status', models.BooleanField(default=False)),
                ('spouse_highest_edu', models.TextField(null=True)),
                ('spouse_dob', models.DateField(null=True)),
                ('candidate', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='agent_candidate.candidateformmodels')),
                ('country_experience', models.ManyToManyField(to='agent_candidate.countrieslistmodel')),
            ],
        ),
    ]
