# Generated by Django 4.0.5 on 2023-01-05 07:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agent_candidate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateformmodels',
            name='agsined_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='agent_candidate.agentuser'),
        ),
    ]
