# Generated by Django 4.0.5 on 2023-01-05 07:39

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('agent_candidate', '0003_rename_agsined_to_candidateformmodels_asigned_to'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AgentUser',
            new_name='CreateUserModel',
        ),
    ]
