# Generated by Django 4.0.6 on 2023-01-07 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent_candidate', '0004_rename_agentuser_createusermodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentformmodel',
            name='specify_country_exp',
            field=models.IntegerField(null=True),
        ),
    ]
