# Generated by Django 4.0.6 on 2023-01-12 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent_candidate', '0005_alter_agentformmodel_specify_country_exp'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentformmodel',
            name='current_location',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='agentformmodel',
            name='job_title',
            field=models.TextField(null=True),
        ),
    ]
