# Generated by Django 4.0.6 on 2023-01-13 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent_candidate', '0007_foldersmodel_candidateformmodels_folder_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentformmodel',
            name='candidate_dob',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='agentformmodel',
            name='candidate_high_edu',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='agentformmodel',
            name='country_experience',
            field=models.ManyToManyField(null=True, to='agent_candidate.countrieslistmodel'),
        ),
        migrations.AlterField(
            model_name='agentformmodel',
            name='preferred_country',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
