# Generated by Django 4.0.6 on 2023-01-27 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent_candidate', '0008_alter_agentformmodel_candidate_dob_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foldersmodel',
            name='folder_name',
            field=models.CharField(max_length=250),
        ),
    ]
