# Generated by Django 4.0.6 on 2023-02-09 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agent_candidate', '0010_createtitlefoldermodel_foldersmodel_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateformmodels',
            name='folder_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='agent_candidate.foldersmodel'),
        ),
    ]
