# Generated by Django 4.0.5 on 2023-05-05 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent_candidate', '0011_alter_candidateformmodels_folder_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentManagementNewAgentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('phone', models.IntegerField()),
            ],
        ),
    ]
