# Generated by Django 4.0.5 on 2023-05-12 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent_candidate', '0012_agentmanagementnewagentmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentmanagementnewagentmodel',
            name='agent_id',
            field=models.BigIntegerField(null=True),
        ),
    ]
