# Generated by Django 4.0.5 on 2023-05-19 03:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agent_candidate', '0013_agentmanagementnewagentmodel_agent_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateFormFilesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachments', models.FileField(null=True, upload_to='AgentManagementCandidateFiles/')),
            ],
        ),
        migrations.AlterField(
            model_name='agentformmodel',
            name='country_experience',
            field=models.ManyToManyField(to='agent_candidate.countrieslistmodel'),
        ),
        migrations.CreateModel(
            name='AgentManagementCandidataFormModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_dob', models.DateField(null=True)),
                ('candidate_high_edu', models.CharField(max_length=500, null=True)),
                ('abroad_exp', models.CharField(max_length=500, null=True)),
                ('sg_pass_detail', models.TextField(null=True)),
                ('applied_pass', models.CharField(max_length=500, null=True)),
                ('specify_note', models.TextField(null=True)),
                ('sat_salary', models.IntegerField(null=True)),
                ('selection_command', models.TextField(null=True)),
                ('candidate_name', models.CharField(max_length=500, null=True)),
                ('kyc', models.CharField(max_length=500, null=True)),
                ('current_location', models.CharField(max_length=500, null=True)),
                ('local_exp', models.CharField(max_length=500, null=True)),
                ('applied_position', models.CharField(max_length=500, null=True)),
                ('spouse_dob', models.TextField(null=True)),
                ('any_physical_challenge', models.BooleanField(null=True)),
                ('specify_physical_challenge', models.CharField(max_length=500, null=True)),
                ('any_relatives', models.BooleanField(null=True)),
                ('specify_any_relatives', models.CharField(max_length=500, null=True)),
                ('agent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='agent_candidate.agentmanagementnewagentmodel')),
                ('attachments', models.ManyToManyField(to='agent_candidate.candidateformfilesmodel')),
            ],
        ),
    ]
