# Generated by Django 4.0.5 on 2023-05-23 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent_candidate', '0014_candidateformfilesmodel_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agentmanagementcandidataformmodel',
            name='attachments',
        ),
        migrations.AddField(
            model_name='agentmanagementcandidataformmodel',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='agentmanagementcandidataformmodel',
            name='upload_cert',
            field=models.FileField(null=True, upload_to='', verbose_name='AMC_upload_cert/'),
        ),
        migrations.AddField(
            model_name='agentmanagementcandidataformmodel',
            name='upload_passport',
            field=models.FileField(null=True, upload_to='AMC_upload_passport/'),
        ),
        migrations.AddField(
            model_name='agentmanagementcandidataformmodel',
            name='upload_resume',
            field=models.FileField(null=True, upload_to='', verbose_name='AMC_upload_resume/'),
        ),
        migrations.AddField(
            model_name='agentmanagementcandidataformmodel',
            name='upload_video',
            field=models.FileField(null=True, upload_to='AMC_upload_video/'),
        ),
        migrations.AddField(
            model_name='agentmanagementcandidataformmodel',
            name='upload_work_video',
            field=models.FileField(null=True, upload_to='', verbose_name='AMC_upload_work_video/'),
        ),
        migrations.DeleteModel(
            name='CandidateFormFilesModel',
        ),
    ]
