# Generated by Django 4.0.5 on 2023-05-24 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent_candidate', '0015_remove_agentmanagementcandidataformmodel_attachments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentmanagementcandidataformmodel',
            name='upload_interview_audio',
            field=models.FileField(null=True, upload_to='', verbose_name='AMC_upload_interview_audio/'),
        ),
    ]
