# Generated by Django 4.0.5 on 2023-05-26 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent_candidate', '0016_agentmanagementcandidataformmodel_upload_interview_audio'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentmanagementcandidataformmodel',
            name='code_number',
            field=models.IntegerField(null=True),
        ),
    ]
