# Generated by Django 4.0.5 on 2023-06-01 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent_candidate', '0017_agentmanagementcandidataformmodel_code_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='AMCandidateUploadCertModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_cert', models.FileField(null=True, upload_to='AMC_upload_cert/')),
            ],
        ),
        migrations.CreateModel(
            name='AMCandidateUploadInterviewAudioModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_interview_audio', models.FileField(null=True, upload_to='AMC_upload_interview_audio/')),
            ],
        ),
        migrations.CreateModel(
            name='AMCandidateUploadPassportModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_passport', models.FileField(null=True, upload_to='AMC_upload_passport/')),
            ],
        ),
        migrations.CreateModel(
            name='AMCandidateUploadResumeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_resume', models.FileField(null=True, upload_to='AMC_upload_resume/')),
            ],
        ),
        migrations.CreateModel(
            name='AMCandidateUploadVideoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_video', models.FileField(null=True, upload_to='AMC_upload_video/')),
            ],
        ),
        migrations.CreateModel(
            name='AMCandidateUploadWorkVideoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_work_video', models.FileField(null=True, upload_to='AMC_upload_work_video/')),
            ],
        ),
        migrations.RemoveField(
            model_name='agentmanagementcandidataformmodel',
            name='upload_cert',
        ),
        migrations.RemoveField(
            model_name='agentmanagementcandidataformmodel',
            name='upload_interview_audio',
        ),
        migrations.RemoveField(
            model_name='agentmanagementcandidataformmodel',
            name='upload_passport',
        ),
        migrations.RemoveField(
            model_name='agentmanagementcandidataformmodel',
            name='upload_resume',
        ),
        migrations.RemoveField(
            model_name='agentmanagementcandidataformmodel',
            name='upload_video',
        ),
        migrations.RemoveField(
            model_name='agentmanagementcandidataformmodel',
            name='upload_work_video',
        ),
        migrations.AddField(
            model_name='agentmanagementcandidataformmodel',
            name='upload_cert',
            field=models.ManyToManyField(to='agent_candidate.amcandidateuploadcertmodel'),
        ),
        migrations.AddField(
            model_name='agentmanagementcandidataformmodel',
            name='upload_interview_audio',
            field=models.ManyToManyField(to='agent_candidate.amcandidateuploadinterviewaudiomodel'),
        ),
        migrations.AddField(
            model_name='agentmanagementcandidataformmodel',
            name='upload_passport',
            field=models.ManyToManyField(to='agent_candidate.amcandidateuploadpassportmodel'),
        ),
        migrations.AddField(
            model_name='agentmanagementcandidataformmodel',
            name='upload_resume',
            field=models.ManyToManyField(to='agent_candidate.amcandidateuploadresumemodel'),
        ),
        migrations.AddField(
            model_name='agentmanagementcandidataformmodel',
            name='upload_video',
            field=models.ManyToManyField(to='agent_candidate.amcandidateuploadvideomodel'),
        ),
        migrations.AddField(
            model_name='agentmanagementcandidataformmodel',
            name='upload_work_video',
            field=models.ManyToManyField(to='agent_candidate.amcandidateuploadworkvideomodel'),
        ),
    ]
