# Generated by Django 4.0.5 on 2023-09-12 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent_candidate', '0018_amcandidateuploadcertmodel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentmanagementcandidataformmodel',
            name='status',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
