# Generated by Django 4.0.5 on 2023-09-19 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client_management', '0016_companyreviewmodel_note'),
        ('agent_candidate', '0019_agentmanagementcandidataformmodel_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateAssignCompanyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(max_length=300, null=True)),
                ('candidates', models.ManyToManyField(to='agent_candidate.agentmanagementcandidataformmodel')),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='client_management.addcompanymodel')),
            ],
        ),
    ]
