# Generated by Django 4.0.5 on 2024-02-06 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent_candidate', '0021_dashboardmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='createusermodel',
            name='phone',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
