# Generated by Django 4.0.5 on 2024-02-28 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent_candidate', '0022_createusermodel_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentmanagementcandidataformmodel',
            name='passport_no',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
