# Generated by Django 4.0.5 on 2024-04-27 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent_candidate', '0023_agentmanagementcandidataformmodel_passport_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentmanagementcandidataformmodel',
            name='alternative_position',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
