# Generated by Django 4.0.5 on 2024-05-12 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent_candidate', '0024_agentmanagementcandidataformmodel_alternative_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentmanagementnewagentmodel',
            name='district',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='agentmanagementnewagentmodel',
            name='place',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
