# Generated by Django 4.0.5 on 2024-07-15 15:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('agent_candidate', '0025_agentmanagementnewagentmodel_district_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='createusermodel',
            name='is_enable',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='GenerateOTPModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secret_key', models.CharField(max_length=100)),
                ('otptime', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
