# Generated by Django 4.0.5 on 2024-09-03 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent_candidate', '0026_createusermodel_is_enable_generateotpmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentmanagementcandidataformmodel',
            name='code_number',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='agentmanagementnewagentmodel',
            name='phone',
            field=models.BigIntegerField(),
        ),
    ]
