# Generated by Django 4.0.5 on 2024-09-03 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent_candidate', '0027_alter_agentmanagementcandidataformmodel_code_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentformmodel',
            name='specify_country_exp',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='agentmanagementcandidataformmodel',
            name='sat_salary',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='candidateformmodels',
            name='phone',
            field=models.BigIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='candidateformmodels',
            name='phone2',
            field=models.BigIntegerField(null=True),
        ),
    ]
