# Generated by Django 4.0.6 on 2023-03-10 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client_management', '0003_newclientmodel_client_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaptchaIssueModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_update', models.DateTimeField(null=True)),
                ('balance', models.IntegerField(null=True)),
                ('error', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='WorkPassModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_no', models.CharField(max_length=300, null=True)),
                ('name', models.CharField(max_length=300, null=True)),
                ('passport_no', models.CharField(max_length=300)),
                ('fin_number', models.CharField(max_length=300, null=True)),
                ('dob', models.DateField()),
                ('status', models.CharField(max_length=300, null=True)),
                ('last_update', models.DateTimeField(null=True)),
                ('error', models.BooleanField(default=False)),
                ('company_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='client_management.addcompanymodel')),
            ],
        ),
    ]
