# Generated by Django 4.0.5 on 2023-03-13 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mom_application', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workpassmodel',
            name='doa',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='workpassmodel',
            name='epass_type',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='workpassmodel',
            name='status',
            field=models.CharField(default='PENDING', max_length=300),
        ),
    ]
