# Generated by Django 4.0.6 on 2023-03-15 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job_advertisement', '0002_jobadvertisementmodel_no_of_vaccancies_and_more'),
        ('mom_application', '0002_workpassmodel_doa_workpassmodel_epass_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workpassmodel',
            name='job',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='job_advertisement.jobadvertisementmodel'),
        ),
    ]
