# Generated by Django 4.0.6 on 2023-03-18 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mom_application', '0003_workpassmodel_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='workpassmodel',
            name='not_available',
            field=models.BooleanField(default=False),
        ),
    ]
