# Generated by Django 4.0.6 on 2023-03-20 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mom_application', '0004_workpassmodel_not_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='workpassmodel',
            name='source',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
