# Generated by Django 4.0.5 on 2023-04-05 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client_management', '0005_remove_companyreviewmodel_company_and_more'),
        ('mom_application', '0006_emailtrackermodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='CPFInvoiceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_date', models.DateTimeField()),
                ('filename', models.CharField(max_length=300)),
                ('datas', models.JSONField(null=True)),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='client_management.addcompanymodel')),
            ],
        ),
    ]
