# Generated by Django 4.0.5 on 2023-04-13 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mom_application', '0007_cpfinvoicemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='AfterApprovalTEPModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_ind_contact', models.IntegerField(null=True)),
                ('employee_sg_contact', models.IntegerField(null=True)),
                ('ipa_to_agent', models.CharField(max_length=300, null=True)),
                ('ipa_to_employer', models.CharField(max_length=300, null=True)),
                ('ipa_expiry_date', models.DateField(null=True)),
                ('payment', models.CharField(max_length=300, null=True)),
                ('arived_traval_date', models.DateField(null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('workpass', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mom_application.workpassmodel')),
            ],
        ),
    ]
