# Generated by Django 4.0.5 on 2023-04-15 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mom_application', '0008_afterapprovaltepmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='afterapprovaltepmodel',
            name='card_exp',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='afterapprovaltepmodel',
            name='card_status',
            field=models.FileField(null=True, upload_to='CardStatus/'),
        ),
        migrations.AddField(
            model_name='afterapprovaltepmodel',
            name='driving',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='afterapprovaltepmodel',
            name='extension_due_20_days',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='afterapprovaltepmodel',
            name='issue',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='afterapprovaltepmodel',
            name='issue_docs',
            field=models.FileField(null=True, upload_to='IssueDocs/'),
        ),
        migrations.AddField(
            model_name='afterapprovaltepmodel',
            name='malaysia_visa',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='afterapprovaltepmodel',
            name='new_valid',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='afterapprovaltepmodel',
            name='other_assignment',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='afterapprovaltepmodel',
            name='thump',
            field=models.DateField(null=True),
        ),
    ]
