# Generated by Django 4.0.5 on 2023-04-17 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mom_application', '0009_afterapprovaltepmodel_card_exp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='afterapprovaltepmodel',
            name='upload_ipa',
            field=models.FileField(null=True, upload_to='UploadIPA/'),
        ),
    ]
