# Generated by Django 4.0.5 on 2023-04-18 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mom_application', '0011_afterapprovaltepmodel_traval_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='afterapprovaltepmodel',
            name='ica_upload',
            field=models.FileField(null=True, upload_to='ICA_File/'),
        ),
    ]
