# Generated by Django 4.0.5 on 2023-04-18 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mom_application', '0012_afterapprovaltepmodel_ica_upload'),
    ]

    operations = [
        migrations.AddField(
            model_name='afterapprovaltepmodel',
            name='notify_acknowledgement',
            field=models.FileField(null=True, upload_to='notify_acknowledgement/'),
        ),
    ]
