# Generated by Django 4.0.5 on 2023-04-24 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mom_application', '0013_afterapprovaltepmodel_notify_acknowledgement'),
    ]

    operations = [
        migrations.AddField(
            model_name='workpassmodel',
            name='pending_doc',
            field=models.FileField(null=True, upload_to='Pending_Doc/'),
        ),
    ]
