# Generated by Django 4.0.5 on 2023-04-25 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mom_application', '0014_workpassmodel_pending_doc'),
    ]

    operations = [
        migrations.AddField(
            model_name='workpassmodel',
            name='apply_copy',
            field=models.FileField(null=True, upload_to='EPOL_ApplyCopy/'),
        ),
    ]
