# Generated by Django 4.0.5 on 2023-04-25 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mom_application', '0015_workpassmodel_apply_copy'),
    ]

    operations = [
        migrations.AddField(
            model_name='workpassmodel',
            name='rejected_reason',
            field=models.FileField(null=True, upload_to='EPOL_Reject_Reason/'),
        ),
    ]
