# Generated by Django 4.0.5 on 2023-05-01 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client_management', '0007_createordermodel_application_id_and_more'),
        ('mom_application', '0017_rename_malaysia_visa_afterapprovaltepmodel_remarks'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailCredentialModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gmail_id', models.CharField(max_length=300, null=True)),
                ('gmail_app_password', models.CharField(max_length=300, null=True)),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='client_management.addcompanymodel')),
            ],
        ),
        migrations.AddField(
            model_name='emailtrackermodel',
            name='email_credential',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mom_application.emailcredentialmodel'),
        ),
    ]
