# Generated by Django 4.0.5 on 2023-05-01 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mom_application', '0018_emailcredentialmodel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtrackermodel',
            name='email_credential',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mom_application.emailcredentialmodel'),
        ),
    ]
