# Generated by Django 4.0.5 on 2023-05-05 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mom_application', '0019_alter_emailtrackermodel_email_credential'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtrackermodel',
            name='receive_date',
            field=models.DateTimeField(null=True),
        ),
    ]
