# Generated by Django 4.0.5 on 2023-05-06 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mom_application', '0020_alter_emailtrackermodel_receive_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailtrackermodel',
            name='read_status',
            field=models.BooleanField(default=True),
        ),
    ]
