# Generated by Django 4.0.5 on 2023-05-08 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client_management', '0007_createordermodel_application_id_and_more'),
        ('mom_application', '0021_emailtrackermodel_read_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreateApplicationQueueModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_date', models.DateField()),
                ('passtype', models.CharField(max_length=300)),
                ('employee_ref', models.CharField(max_length=300)),
                ('assigned_by', models.CharField(max_length=300)),
                ('staff', models.CharField(max_length=300)),
                ('status', models.CharField(max_length=300)),
                ('upload_docs', models.FileField(null=True, upload_to='ApplicationQueue/')),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='client_management.addcompanymodel')),
            ],
        ),
    ]
