# Generated by Django 4.0.5 on 2023-05-09 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mom_application', '0022_createapplicationqueuemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='createapplicationqueuemodel',
            name='voice_record',
            field=models.FileField(null=True, upload_to='AppQueueVoiceRecord/'),
        ),
    ]
