# Generated by Django 4.0.5 on 2023-05-13 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mom_application', '0023_createapplicationqueuemodel_voice_record'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cpfinvoicemodel',
            name='filename',
        ),
        migrations.AddField(
            model_name='cpfinvoicemodel',
            name='csv_invoice',
            field=models.FileField(null=True, upload_to='CPF_CSV_Invoice/'),
        ),
        migrations.AddField(
            model_name='cpfinvoicemodel',
            name='pdf_invoice',
            field=models.FileField(null=True, upload_to='CPF_PDF_Invoice/'),
        ),
        migrations.AlterField(
            model_name='cpfinvoicemodel',
            name='upload_date',
            field=models.DateTimeField(null=True),
        ),
    ]
