# Generated by Django 4.0.5 on 2023-06-09 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client_management', '0009_buyingsellingmodel_video'),
        ('mom_application', '0026_emailattachmentsmodel_emailtrackermodel_attachments'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerEntryForm1Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ic_number', models.CharField(max_length=500, null=True)),
                ('name', models.CharField(max_length=500, null=True)),
                ('dob', models.DateField(null=True)),
                ('nationality', models.CharField(max_length=500, null=True)),
                ('contact_number', models.IntegerField(null=True)),
                ('ic_copy_file', models.FileField(null=True, upload_to='CPF_Entry_Form1_IC_Copy/')),
                ('referby', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='client_management.newclientmodel')),
            ],
        ),
    ]
