# Generated by Django 4.0.5 on 2023-06-10 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client_management', '0009_buyingsellingmodel_video'),
        ('mom_application', '0027_customerentryform1model'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerEntryForm2Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month_year', models.DateField(null=True)),
                ('no_of_fulltime', models.IntegerField(null=True)),
                ('no_of_parttime', models.IntegerField(null=True)),
                ('declaration', models.CharField(max_length=500)),
                ('draft_upload', models.FileField(null=True, upload_to='CPF_Entry_Form2_DraftUpload/')),
                ('company_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='client_management.addcompanymodel')),
            ],
        ),
    ]
