# Generated by Django 4.0.5 on 2023-07-07 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mom_application', '0028_customerentryform2model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workpassmodel',
            name='dob',
            field=models.DateField(null=True),
        ),
    ]
