# Generated by Django 4.0.5 on 2023-08-02 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mom_application', '0029_alter_workpassmodel_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='cpfinvoicemodel',
            name='contribution_date_month',
            field=models.DateField(null=True),
        ),
    ]
