# Generated by Django 4.0.5 on 2023-09-20 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mom_application', '0030_cpfinvoicemodel_contribution_date_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createapplicationqueuemodel',
            name='employee_ref',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
