# Generated by Django 4.0.5 on 2024-09-03 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mom_application', '0032_alter_createapplicationqueuemodel_employee_ref'),
    ]

    operations = [
        migrations.AlterField(
            model_name='afterapprovaltepmodel',
            name='employee_ind_contact',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='afterapprovaltepmodel',
            name='employee_sg_contact',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='captchaissuemodel',
            name='balance',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='customerentryform1model',
            name='contact_number',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='customerentryform2model',
            name='no_of_fulltime',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='customerentryform2model',
            name='no_of_parttime',
            field=models.BigIntegerField(null=True),
        ),
    ]
