# Generated by Django 4.0.5 on 2024-10-08 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mom_application', '0033_alter_afterapprovaltepmodel_employee_ind_contact_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailcredentialmodel',
            name='gmail_working_status',
            field=models.BooleanField(default=True),
        ),
    ]
