# Generated by Django 4.0.5 on 2022-12-28 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mioapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RegesiterForm',
            new_name='CandidateForm',
        ),
    ]
