# Generated by Django 4.0.5 on 2022-12-28 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mioapp', '0002_rename_regesiterform_candidateform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateform',
            name='phone',
            field=models.IntegerField(unique=True),
        ),
    ]
