# Generated by Django 4.0.5 on 2022-12-29 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mioapp', '0003_alter_candidateform_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateform',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
