# Generated by Django 4.0.5 on 2022-12-29 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mioapp', '0004_candidateform_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentFormModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('phone', models.IntegerField(unique=True)),
                ('experience', models.IntegerField()),
                ('qualification', models.CharField(max_length=150)),
                ('passport_no', models.CharField(max_length=150)),
                ('remarks', models.CharField(max_length=500)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
