# Generated by Django 4.0.6 on 2023-02-15 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobAdvertisementModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_app', models.DateField()),
                ('maturity_date', models.DateField()),
                ('expiry_date', models.DateField()),
                ('job_code', models.CharField(max_length=300)),
                ('range_field', models.IntegerField(null=True)),
                ('designation', models.CharField(max_length=500)),
                ('comp_name', models.CharField(max_length=500)),
                ('date_of_review', models.DateField(null=True)),
                ('no_of_app', models.IntegerField(null=True)),
                ('emp_name', models.CharField(max_length=300)),
            ],
        ),
    ]
