# Generated by Django 4.0.6 on 2023-03-15 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client_management', '0003_newclientmodel_client_id'),
        ('job_advertisement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobadvertisementmodel',
            name='no_of_vaccancies',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='jobadvertisementmodel',
            name='comp_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='client_management.addcompanymodel'),
        ),
        migrations.AlterField(
            model_name='jobadvertisementmodel',
            name='emp_name',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
