# Generated by Django 4.0.5 on 2023-07-12 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_advertisement', '0002_jobadvertisementmodel_no_of_vaccancies_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServerStorageInfoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_storage', models.IntegerField()),
                ('user_storage', models.IntegerField()),
                ('total_percent_used', models.IntegerField()),
            ],
        ),
    ]
