# Generated by Django 4.0.5 on 2023-07-12 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_advertisement', '0003_serverstorageinfomodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serverstorageinfomodel',
            name='total_percent_used',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='serverstorageinfomodel',
            name='total_storage',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='serverstorageinfomodel',
            name='user_storage',
            field=models.IntegerField(null=True),
        ),
    ]
