# Generated by Django 4.0.5 on 2023-07-12 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_advertisement', '0004_alter_serverstorageinfomodel_total_percent_used_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serverstorageinfomodel',
            name='total_percent_used',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='serverstorageinfomodel',
            name='user_storage',
            field=models.FloatField(null=True),
        ),
    ]
