# Generated by Django 4.0.5 on 2023-12-22 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_advertisement', '0008_remove_mytodomodel_task_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobadvertisementmodel',
            name='range_field',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
