# Generated by Django 4.0.5 on 2024-09-03 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_advertisement', '0010_realtimeuseractivemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobadvertisementmodel',
            name='no_of_app',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='jobadvertisementmodel',
            name='no_of_vaccancies',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='serverstorageinfomodel',
            name='total_storage',
            field=models.BigIntegerField(null=True),
        ),
    ]
