# Generated by Django 4.0.5 on 2024-09-05 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_advertisement', '0011_alter_jobadvertisementmodel_no_of_app_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serverstorageinfomodel',
            name='total_percent_used',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='serverstorageinfomodel',
            name='total_storage',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='serverstorageinfomodel',
            name='user_storage',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
