# Generated by Django 4.0.5 on 2024-09-11 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_advertisement', '0013_staffmaintenancemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='realtimeuseractivemodel',
            name='location',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
