# Generated by Django 4.0.5 on 2024-09-23 08:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client_management', '0031_addcompanymodel_create_orderid_track'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('job_advertisement', '0014_realtimeuseractivemodel_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeerPersonalNotesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_date', models.DateField()),
                ('remarks', models.TextField()),
                ('voice', models.FileField(null=True, upload_to='EmployeerPersonalNotesVoices/')),
                ('status', models.BooleanField(default=False)),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='client_management.addcompanymodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
