# Generated by Django 4.0.6 on 2023-01-31 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent_candidate', '0010_createtitlefoldermodel_foldersmodel_title'),
        ('work_management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='createtaskmodel',
            name='asigned_to',
        ),
        migrations.AddField(
            model_name='createtaskmodel',
            name='asigned_to',
            field=models.ManyToManyField(to='agent_candidate.createusermodel'),
        ),
    ]
