# Generated by Django 4.0.6 on 2023-02-06 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_management', '0002_remove_createtaskmodel_asigned_to_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachmentmodel',
            name='voice_record',
            field=models.FileField(null=True, upload_to='VoiceRecord/'),
        ),
    ]
