# Generated by Django 4.0.6 on 2023-02-06 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_management', '0003_attachmentmodel_voice_record'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attachmentmodel',
            name='voice_record',
        ),
        migrations.AddField(
            model_name='createtaskmodel',
            name='voice_record',
            field=models.FileField(null=True, upload_to='VoiceRecord/'),
        ),
    ]
