# Generated by Django 4.0.6 on 2023-03-24 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_management', '0004_remove_attachmentmodel_voice_record_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createtaskmodel',
            name='company_name',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='createtaskmodel',
            name='employer_name',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
