# Generated by Django 4.0.5 on 2023-09-08 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('work_management', '0006_alter_createtaskmodel_company_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddSubjectModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.TextField(null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='createtaskmodel',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='work_management.addsubjectmodel'),
        ),
    ]
