# Generated by Django 4.0.6 on 2023-02-27 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewClientModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=300)),
                ('phone_number', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AddCompanyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_id', models.CharField(max_length=500)),
                ('company_name', models.CharField(max_length=500)),
                ('roc', models.CharField(max_length=300)),
                ('email', models.CharField(max_length=300)),
                ('contact_person', models.CharField(max_length=300)),
                ('contact_number', models.IntegerField()),
                ('singpass_id', models.CharField(max_length=300, null=True)),
                ('singpass_password', models.CharField(max_length=300, null=True)),
                ('qr_code', models.BooleanField(default=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client_management.newclientmodel')),
            ],
        ),
    ]
