# Generated by Django 4.0.6 on 2023-03-03 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_management', '0002_alter_addcompanymodel_contact_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newclientmodel',
            name='client_id',
            field=models.IntegerField(null=True),
        ),
    ]
