# Generated by Django 4.0.6 on 2023-03-28 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client_management', '0003_newclientmodel_client_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyReviewModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roc', models.CharField(max_length=300, null=True)),
                ('status_date', models.DateField()),
                ('status', models.CharField(max_length=300)),
                ('quota_date', models.DateField()),
                ('size', models.IntegerField()),
                ('spass_sp', models.IntegerField()),
                ('spass_ex', models.IntegerField()),
                ('spass_add', models.IntegerField()),
                ('ep', models.IntegerField()),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='client_management.addcompanymodel')),
            ],
        ),
    ]
