# Generated by Django 4.0.6 on 2023-03-29 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client_management', '0004_companyreviewmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyreviewmodel',
            name='company',
        ),
        migrations.RemoveField(
            model_name='companyreviewmodel',
            name='roc',
        ),
        migrations.AddField(
            model_name='addcompanymodel',
            name='company_review',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='client_management.companyreviewmodel'),
        ),
        migrations.AlterField(
            model_name='companyreviewmodel',
            name='ep',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='companyreviewmodel',
            name='quota_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='companyreviewmodel',
            name='size',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='companyreviewmodel',
            name='spass_add',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='companyreviewmodel',
            name='spass_ex',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='companyreviewmodel',
            name='spass_sp',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='companyreviewmodel',
            name='status',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='companyreviewmodel',
            name='status_date',
            field=models.DateField(null=True),
        ),
    ]
