# Generated by Django 4.0.5 on 2023-04-07 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client_management', '0005_remove_companyreviewmodel_company_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreateOrderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateField(auto_now=True)),
                ('ref_id', models.CharField(max_length=300)),
                ('description', models.TextField(null=True)),
                ('pass_type', models.CharField(max_length=300, null=True)),
                ('no_of_vacancies', models.IntegerField(null=True)),
                ('voice_record', models.FileField(null=True, upload_to='CreateOrder/')),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='client_management.addcompanymodel')),
            ],
        ),
    ]
