# Generated by Django 4.0.5 on 2023-06-07 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client_management', '0007_createordermodel_application_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuyingSellingAttachmentsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachments', models.FileField(null=True, upload_to='BuyingSelling/')),
            ],
        ),
        migrations.CreateModel(
            name='BuyingSellingModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submit_date', models.DateField()),
                ('business_type', models.CharField(max_length=500, null=True)),
                ('address', models.TextField(null=True)),
                ('rental_deposite', models.CharField(max_length=500, null=True)),
                ('sales_details', models.TextField(null=True)),
                ('staff_needed', models.IntegerField(null=True)),
                ('company_details', models.TextField(null=True)),
                ('take_over_fee', models.CharField(max_length=500, null=True)),
                ('recommended_buyers', models.TextField(null=True)),
                ('remarks', models.TextField(null=True)),
                ('status', models.CharField(max_length=500, null=True)),
                ('attachments', models.ManyToManyField(to='client_management.buyingsellingattachmentsmodel')),
                ('employeer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='client_management.newclientmodel')),
            ],
        ),
    ]
