# Generated by Django 4.0.5 on 2023-06-07 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_management', '0008_buyingsellingattachmentsmodel_buyingsellingmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyingsellingmodel',
            name='video',
            field=models.FileField(null=True, upload_to='BuyingSellingVideo/'),
        ),
    ]
