# Generated by Django 4.0.5 on 2023-06-20 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client_management', '0009_buyingsellingmodel_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaySlipModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payslip_date_from', models.DateField(null=True)),
                ('payslip_date_to', models.DateField(null=True)),
                ('employee_name', models.CharField(max_length=300, null=True)),
                ('basic_pay', models.IntegerField(null=True)),
                ('total_allowance', models.IntegerField(null=True)),
                ('advance', models.IntegerField(null=True)),
                ('employee_cpf_deduction', models.IntegerField(null=True)),
                ('payment_date', models.DateField(null=True)),
                ('mode_of_payment', models.CharField(max_length=300, null=True)),
                ('overtime_payment_period', models.IntegerField(null=True)),
                ('overtime_work_hours', models.IntegerField(null=True)),
                ('other_additional', models.IntegerField(null=True)),
                ('employee_cpf_contribution', models.IntegerField(null=True)),
                ('net_pay', models.IntegerField(null=True)),
                ('total_deduction', models.IntegerField(null=True)),
                ('employeer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='client_management.newclientmodel')),
            ],
        ),
    ]
