# Generated by Django 4.0.5 on 2023-06-22 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_management', '0011_alter_payslipmodel_employeer'),
    ]

    operations = [
        migrations.AddField(
            model_name='payslipmodel',
            name='designation',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='payslipmodel',
            name='fin_number',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
