# Generated by Django 4.0.5 on 2023-06-26 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mom_application', '0028_customerentryform2model'),
        ('client_management', '0012_payslipmodel_designation_payslipmodel_fin_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payslipmodel',
            name='designation',
        ),
        migrations.RemoveField(
            model_name='payslipmodel',
            name='employee_name',
        ),
        migrations.RemoveField(
            model_name='payslipmodel',
            name='employeer',
        ),
        migrations.RemoveField(
            model_name='payslipmodel',
            name='fin_number',
        ),
        migrations.AddField(
            model_name='payslipmodel',
            name='after_approved_tep',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mom_application.afterapprovaltepmodel'),
        ),
    ]
