# Generated by Django 4.0.5 on 2023-09-07 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_management', '0013_remove_payslipmodel_designation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyreviewmodel',
            name='new_ind',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='companyreviewmodel',
            name='new_prc',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='companyreviewmodel',
            name='new_sp',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='companyreviewmodel',
            name='new_wp',
            field=models.IntegerField(null=True),
        ),
    ]
