# Generated by Django 4.0.5 on 2023-09-08 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_management', '0014_companyreviewmodel_new_ind_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyreviewmodel',
            name='new_sfa',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
