# Generated by Django 4.0.5 on 2023-09-15 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_management', '0015_companyreviewmodel_new_sfa'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyreviewmodel',
            name='note',
            field=models.TextField(null=True),
        ),
    ]
