# Generated by Django 4.0.5 on 2023-09-21 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client_management', '0016_companyreviewmodel_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuyerFormModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_number', models.IntegerField(null=True)),
                ('whatsapp_number', models.IntegerField(null=True)),
                ('requirement', models.TextField(null=True)),
                ('employeer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='client_management.newclientmodel')),
            ],
        ),
    ]
