# Generated by Django 4.0.5 on 2023-09-23 05:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client_management', '0018_alter_buyerformmodel_employeer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyerformmodel',
            name='employeer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='client_management.newclientmodel'),
        ),
    ]
