# Generated by Django 4.0.5 on 2024-03-27 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_management', '0019_alter_buyerformmodel_employeer'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyreviewmodel',
            name='local_col',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
