# Generated by Django 4.0.5 on 2024-05-25 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_management', '0022_alter_companyreviewmodel_new_ind_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinanceAuditModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_end', models.DateTimeField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='companyreviewmodel',
            name='finance',
            field=models.ManyToManyField(to='client_management.financeauditmodel'),
        ),
    ]
