# Generated by Django 4.0.5 on 2024-06-03 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_management', '0023_financeauditmodel_companyreviewmodel_finance'),
    ]

    operations = [
        migrations.AddField(
            model_name='createordermodel',
            name='dropbox_url',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='createordermodel',
            name='tiny_url',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
