# Generated by Django 4.0.5 on 2024-07-17 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client_management', '0025_createordermodel_require_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CPFTrackerCompanyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthly_update', models.JSONField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='addcompanymodel',
            name='cpf_tracker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='client_management.cpftrackercompanymodel'),
        ),
    ]
