# Generated by Django 4.0.5 on 2024-08-05 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_management', '0027_cpftrackercompanymodel_hr_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyreviewmodel',
            name='finance',
        ),
        migrations.AddField(
            model_name='companyreviewmodel',
            name='date_of_incorp',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='companyreviewmodel',
            name='finance_year_end',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.DeleteModel(
            name='FinanceAuditModel',
        ),
    ]
