# Generated by Django 4.0.5 on 2024-08-26 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_management', '0028_remove_companyreviewmodel_finance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='addcompanymodel',
            name='director_name',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
