# Generated by Django 4.0.5 on 2024-09-16 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_management', '0030_alter_addcompanymodel_contact_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='addcompanymodel',
            name='create_orderid_track',
            field=models.JSONField(null=True),
        ),
    ]
