# Generated by Django 4.0.5 on 2024-09-28 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_management', '0031_addcompanymodel_create_orderid_track'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoiceChangerUploadFileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio', models.FileField(null=True, upload_to='VoiceChangerUploadFile/')),
            ],
        ),
    ]
