# Generated by Django 4.0.5 on 2024-10-04 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_management', '0032_voicechangeruploadfilemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='createordermodel',
            name='exist_modified_audio',
            field=models.FileField(null=True, upload_to='CreateOrderModifiedAudio/'),
        ),
    ]
