# Generated by Django 4.0.5 on 2024-12-05 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_management', '0033_createordermodel_exist_modified_audio'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdiraProcessedLeadsModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adira_id', models.BigIntegerField(null=True)),
            ],
        ),
    ]
